### ISSUE TITLE
Have a problem while installing

### ISSUE THREAD

**Issue by oghuzima** [happypandax/server#37]
I just do the step from building, and have problem like this..
already install Visual C++ 14.0, but too much problem there.. need advice..
thank you
![problems](https://user-images.githubusercontent.com/28099805/30001364-3818210e-90b6-11e7-98cc-0cae03d39f54.png)

**Comment by emmauss** [comment]
there is a warning below those instructions, telling you to download bintray if you get a problem with it. download from here and install it using `pip install *filename*`, while env is active.also, please update to the latest commit, and use the readme on the main github page for installation. @Pewpews   you may want to update the docs.

**Comment by g2744092** [comment]
On Windows, I just finished installing it and it wouldn't run. It turns out you need Python Image Library (PIL) also. I downloaded the "PIL-2.0+dummy-py2.py3-none-any.whl" from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow and it'll download the latest Pillow as well as maintain compatibility with PIL.

**Comment by Pewpews** [comment]
I updated the instructions. Installing should be easier than ever with the help of `bootstrap.py`.
